# Generated by Django 4.1.2 on 2022-11-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=555.89, max_digits=5),
            preserve_default=False,
        ),
    ]
